<style>
    @media print{
        body {
            position:relative !important;
        }
        .celltag_new_page {
            page-break-before: always !important;
        }
    }
</style>
# COMPSCI 371D Homework 9

### Problem 0 (3 points)

## Part 1: Back-Propagation

### Problem 1.1 (Exam Style)

Calculate gradient of ReLU and express in terms of sign function.

When X < 0, differentiation is 0, sign(a) is -1.
When X > 0, differentiation is 1, sign (a) is 1.
When X = 0, it is undefined by we define it to be 1/2, sign (a) = 0.

So, how do we transform the sign(a) into an expression for the derivative of the ReLU function?
        
Divide by 2, and add one half.

(sign(a)/2) + 1/2 = 

          {1 if a > 0}
          {1/2 if a = 0}
          {0 if a < 0}
          



### Problem 1.2 (Exam Style Except for Code)

$$
\begin{eqnarray*}
\text{shape}(g_y) &=& (1,1) \\
\text{shape}(J_{\mathbf{v}}) &=& (1,3) \\
\text{shape}(\mathbf{g}_{\mathbf{v}}) &=& (1,3) \\
\text{shape}(H_{\mathbf{a}}) &=& (1,2) \\
\text{shape}(\mathbf{g}_{\mathbf{a}}) &=& (1,2) \\
\text{shape}(J_{\mathbf{u}}) &=& (2,6) \\
\text{shape}(\mathbf{g}_{\mathbf{u}}) &=& (1,6) \\
\text{shape}(\mathbf{g}_{\mathbf{w}}) &=& (1,9)
\end{eqnarray*}
$$

1.2.2.1: y-yn


1.2.2.2: (sign(v1a1 + v2a2 + v3)/2 + 1/2) * [a1, a2, 1]


1.2.2.3: (sign(v1a1 + v2a2 + v3)/2 + 1/2) * [v1, v2]


1.2.2.4: [p'(u1x1 + u2x2 + u3x3) * [x1, x2, x3, 0, 0, 0]]
         [p'(u4x1 + u5x2 + u6x3) * [0, 0, 0, x1, x2, x3]]
         
         
1.2.3.1: -2


1.2.3.2: [0 8 1]


1.2.3.3: [4 1]


1.2.3.4: 

         [0 0 0 0 0 0]
         [0 0 0 1 3 2]



(Work is below)

$$
g_y = y - y_n
$$

$$
J_v = \frac{y'}{v} = p'(Va+b) * a = (\frac{sign(v_1a_1 + v_2a_2 + v_3)}{2} +\frac{1}{2} * [a_1, a_2, 1]
$$

$$
\begin{bmatrix}
p'(u_1x_1 + u_2x_2 + u_3x_3) * [x_1, x_2, x_3, 0, 0, 0] \\
p'(u_4x_1 + u_5x_2 + u_6x_3) * [0, 0, 0,x_1, x_2, x_3] 
\end{bmatrix}
$$

$$
\begin{eqnarray*}
g_y &=& y - yn \\ 


J_{\mathbf{v}} &=&  derivative(y)/derivative(v) = p'(Va + b) * a = (sign(v1a1 + v2a2 + v3)/2 + 1/2) * [a1, a2, 1]\\ 

H_{\mathbf{a}} &=& derivative(y)/derivative(a) = (sign(v1a1 + v2a2 + v3)/2 + 1/2) * [v1, v2]\\

J_{\mathbf{u}} &=& derivative(a)/derivative(u) = 
[p'(u1x1 + u2x2 + u3x3) * [x1, x2, x3, 0, 0, 0]]

[p'(u4x1 + u5x2 + u6x3) * [0, 0, 0, x1, x2, x3]]
\end{eqnarray*}
$$

and for the given numerical values
// Plug in values t
$$
\begin{eqnarray*}
g_y &=& -2

y = p((p(U * x) * V) + b) -> 

U*x = [2 * 1 + -1 * 3 + 0 * 2]
      [-1 * 1 + 1 * 3 + 2 * 3] = 
      
      [-1]
      [8]
      
 p[-1]  [0]
  [8] = [8]
  
  [0]
  [8] * v = 
  
  0 * 4 + 8 * 1 = 8.
  
  8 - 3 = 5 = y.
  
  yn = 7.
  
  y - yn = -2.
  
  
      \\ 
J_{\mathbf{v}} &=& [0 8 1]

P(Ux) = [0]
        [8]
        
sign((4 * 0 + 1 * 8 + -3)/2) + 1/2) * [0 8 1]   \\
sign(5/2)/2 + 1/2 = 1/2 + 1/2 = 1

1 * [0 8 1] = [0 8 1]

H_{\mathbf{a}} &=& [4 1] \\

Same as above but times [v1 v2]

1 * [4 1] = [4 1]


J_{\mathbf{u}} &=& [0 0 0 0 0 0]
                   [0 0 0 1 3 2]


[p'(u1x1 + u2x2 + u3x3) * [x1, x2, x3, 0, 0, 0]]

[p'(u4x1 + u5x2 + u6x3) * [0, 0, 0, x1, x2, x3]]

[p'(2 * 1 + -1 * 3 + 0 * 2) * [1 3 2 0 0 0]]
[p'(1 * -1 + 3 * 1 + 2 * 3) * [0 0 0 1 3 2]]

[p'(-1) * ...]
[p'(8) * ...]

p'(-1) = 0
p'(8) = 1

[0 0 0 0 0 0]
[0 0 0 1 3 2]

\end{eqnarray*}
$$

In [15]:
import numpy as np

def gradient(xn, yn, U, V, b):
    
    a = ReLU(np.dot(U, xn))
    print("a", a)
    y = ReLU(np.dot(V, a) + b)
    print("y", y)
    gy = y - yn
    print("gy", gy)
    Jv = ((sign(np.dot(V, a) + b))/2 + 1/2) * np.array([*list(a), 1])
    print("Jv", Jv)
    Ha = ((sign(np.dot(V, a) + b))/2 + 1/2) * np.array([*list(V)])
    print("Ha", Ha)
    
    """
    ju1 = (sign(np.dot(U,xn))/2 + 1/2)
    print("ju1", ju1)
    ju2 = np.array([[*list(xn), 0, 0, 0],[0, 0, 0, *list(xn)]])
    print("ju2", ju2)
    """
    derivative = sign(np.dot(U,xn))/2 + 1/2
    print("derivative", derivative)
    row1 = derivative[0] * np.array([*list(xn), 0, 0, 0])
    row2 = derivative[1] * np.array([0, 0, 0, *list(xn)])
    print("row1", row1)
    print("row2", row2)
    Ju = np.concatenate((row1, row2)).reshape(2,6)
#    Ju = np.array([ju1 @ ju2])
    print("Ju",Ju)
    gv = gy * Jv
    print("gv", gv)
    ga = gy * Ha
    print("ga", ga)
    gu = np.dot(ga, Ju)
    gw = np.array([*list(gu), *list(gv)])
    return gw
    
def ReLU(c):
    return np.maximum(c, 0)

def sign(c):
    return np.sign(c)
                    
gradient(np.array([1,3,2]), 7, np.array([[2,-1,0],[-1,1,3]]), np.array([4,1]), -3)
            

a [0 8]
y 5
gy -2
Jv [0. 8. 1.]
Ha [4. 1.]
derivative [0. 1.]
row1 [0. 0. 0. 0. 0. 0.]
row2 [0. 0. 0. 1. 3. 2.]
Ju [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 3. 2.]]
gv [ -0. -16.  -2.]
ga [-8. -2.]


array([  0.,   0.,   0.,  -2.,  -6.,  -4.,  -0., -16.,  -2.])

### Problem 1.3 (Exam Style)

Yes, valid convolution. Kernel is v and the thing we are convolving on is a.

## Part 2: MNIST Digit Recognition

### Problem 2.1